//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iscacTransportes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distancia
    {
        public int DistanciaID { get; set; }
        public Nullable<int> OrigemID { get; set; }
        public Nullable<int> DestinoID { get; set; }
        public Nullable<decimal> Distancia1 { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Carga { get; set; }
    }
}
