//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iscacTransportes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RotaFinal
    {
        public int RotaID { get; set; }
        public Nullable<int> Antecessor { get; set; }
        public Nullable<int> Sucessor { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public string UserName { get; set; }
    }
}
