//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iscacTransportes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewCaminho
    {
        public int CaminhoID { get; set; }
        public Nullable<int> RotaNumero { get; set; }
        public Nullable<int> DestinoFK { get; set; }
        public string UserName { get; set; }
        public string Nome { get; set; }
        public string Rua { get; set; }
        public string CodigoPostal { get; set; }
        public string Localidade { get; set; }
        public Nullable<int> Ordem { get; set; }
        public string Pais { get; set; }
        public Nullable<int> Carga { get; set; }
    }
}
